name: mood_tracker_assessment
description: "Marcel created this Mood Tracker app for a technical assessment"
publish_to: "none"
version: 0.0.3+3

environment:
  sdk: ^3.7.0

dependencies:
  confetti: ^0.8.0
  crypto: ^3.0.6
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_slidable: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker_plus: ^2.7.2
  intl: ^0.19.0
  table_calendar: ^3.1.3
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  rename: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/sounds/
    - assets/l10n/
