name: mood_tracker_assessment
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  table_calendar: ^3.2.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  rename: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/sounds/
